name: Publicar novas releases do Plugin

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        gem install sass
        npm install
        grunt
        
    - name: Create artifact
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -X -r build/orbita.zip . -x *.git* node_modules/\* .* "*/\.*" CODE_OF_CONDUCT.md CONTRIBUTING.md ISSUE_TEMPLATE.md PULL_REQUEST_TEMPLATE.md *.dist build**

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
          name: graphql-api
          path: build/orbita.zip
          
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: build/orbita.zip application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
