name: Update version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Add new version"
        required: true

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update version
      working-directory: ./
      run: |
        sed -i "14d" orbita.php
        sed -i "14i \ * Version:         ${{ github.event.inputs.version }}" orbita.php
        sed -i "43d" orbita.php
        sed -i "43i define( 'ORBITA_VERSION', '${{ github.event.inputs.version }}' );" orbita.php
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "Atualiza para a versão ${{ github.event.inputs.version }}"

    - name: Push
      uses: ad-m/github-push-action@master